### ISSUE TITLE
windows向けがx86ビルドしか含まれていない

### ISSUE THREAD

**Issue by 5ym** [Harekaze/pvr.epgstation#1]
表題の通りですkodiをmicrosoft storeからインストールした場合は64bitになってます32bit版を入れる必要がありました。

**Comment by mzyy94** [comment]
なるほど。。KodiのWindows 64bitは[v18 Leiaからサポートされるようになった](https://kodi.tv/article/kodi-v18-windows-64-bit-here)比較的新しいプラットフォームなので、シェアとしては32bit版の方が多いと思っていましたがStore版の存在がありましたね。。
次のバージョンでビルド対象を新たに増やす形で対応しようと思いますので、少々お待ちいただければと🙏

**Comment by mzyy94** [comment]
Kodiインストーラー版としても、Windows 32bitは非推奨でした。（久しくWindowsで使ってなかったので気づかず。）ビルド対象を増やすのではなく、Windowsも64bitを標準に入れ替える形で変更していきます。
<img width="420" alt="Screenshot 2020-07-27 22 38 59" src="https://user-images.githubusercontent.com/2971112/88548366-f89e1d80-d059-11ea-9322-eb38d0f02a29.png">

**Comment by mzyy94** [comment]
Fixed by afac31b55cc3e683292d833bc2bbfc8050bd3d44 and a97540be03518114b490c444e545f8aea39ad8b9
