### ISSUE TITLE
要望:ライブ視聴と録画した番組の再生について

### ISSUE THREAD

**Issue by stu2005** [Harekaze/pvr.epgstation#3]
無変換で視聴するオプションがほしいです。いかんせんepgstationのマシンが非力なものですから、再生がまともにできません。

**Comment by 5ym** [comment]
ストリーミングのオプション番号の指定ができると思いますが、今一度epgstationとこちらのドキュメントをご確認ください

**Comment by stu2005** [comment]
お騒がせして申し訳ありませんでした
