### ISSUE TITLE
録画済みリストが24件までしか表示されない

### ISSUE THREAD

**Issue by nidixx** [Harekaze/pvr.epgstation#6]
EPGStationのAPI (/api/recorded) がデフォルトで最大24件しか返さないためのようです。 (limitパラメータ) 
オプション画面で設定できるか、limitにあらかじめ大きい数値を与えてしまっても良いかと思いました。

**Comment by mzyy94** [comment]
ご報告ありがとうございます。見落としてました
65535くらいの大きな値をセットして解消します

**Comment by mzyy94** [comment]
Fixed by 61a169ed383c08a6fdee400ebd9832123fe8d72c

[v0.0.8](https://github.com/Harekaze/pvr.epgstation/releases/tag/v0.0.8)で修正されました
